import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/younitoday">YOUnitoday</Link>
        </li>
        <li>
          <Link to="/coursesdetails">CoursesDetails</Link>
        </li>
        <li>
          <Link to="/younitodayprogrampricing">YOUnitodayProgramPricing</Link>
        </li>
        <li>
          <Link to="/singlementordetails">Singlementordetails</Link>
        </li>
        <li>
          <Link to="/younitodayshop">YOUnitodayShop</Link>
        </li>
        <li>
          <Link to="/younitodayjoinasmentor">YOUnitodayJoinAsMentor</Link>
        </li>
        <li>
          <Link to="/younitodayprograms">YOUnitodayPrograms</Link>
        </li>
        <li>
          <Link to="/allmentors">Allmentors</Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
